### PR TITLE
fix(ROS2TFClient): Use correct action type for ROS2 tf2_web_republisher

### LINKED ISSUE #948: Bug: ROS2TFClient uses incorrect hardcoded actionType for tf2_web_republisher
**Description**
The ROS2TFClient component uses a hardcoded action type (tf2_web_republisher_msgs/TFSubscription) . This makes the client incompatible with standard ROS 2  tf2_web_republisher, which expect the action type to be tf2_web_republisher_interfaces/action/TFSubscription.  
I have created a Pull Request that should resolve this issue. After applying the fix, I was able to successfully display PointCloud2 visualizations from a ROS 2 backend. If helpful, I can also contribute relevant examples and tutorials.

- Library Version: Latest from develop branch
- ROS Version: ROS2 Kilted
- Platform / OS: Ubuntu 24.04

**Steps To Reproduce**

```  
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>FROS2TFClient Test</title>
    <script src="https://unpkg.com/eventemitter3@latest/dist/eventemitter3.umd.min.js"></script>
    <script src="./js/roslib.umd.js"></script>
</head>

<body>
    <h1>FROS2TFClient Test</h1>
    <script>
        const ros = new ROSLIB.Ros({
            url: 'ws://localhost:9090'
        });
        const tfClient = new ROSLIB.ROS2TFClient({
            ros: ros,
            fixedFrame: 'map',
            angularThres: 0.01,
            transThres: 0.01,
            rate: 10.0
        });
        tfClient.subscribe('world', (transform) => {
        });
        console.log(tfClient)
    </script>
</body>

</html>
```

**Expected Behavior**

The tfClient.subscribe call should succeed. No errors should appear in the rosbridge_server log. 

**Actual Behavior**
```[rosbridge_websocket-1] [ERROR] [timestamp] [rosbridge_websocket]: [Client <client_id>] send_action_goal InvalidModuleException: send_action_goal:/tf2_web_republisher:1```

### PR DESCRIPTION
**Pull request by linglitel**
In the ROS2 version of tf2-web-republisher, the correct Action name should be tf2_web_republisher_interfaces/action/TFSubscription. Fixing this will allow PointCloud2 to be displayed correctly on the web page. This change has been tested on ROS2 Kilted, Ubuntu 24.04 and works for me.

**Public API Changes**

None

**Description**
 
The ROS2TFClient component currently uses a hardcoded action type (tf2_web_republisher_msgs/TFSubscription) This makes the client incompatible with standard ROS 2 tf2_web_republisher, which expect the action type to be tf2_web_republisher_interfaces/action/TFSubscription.
This commit corrects the hardcoded action type to the proper ROS 2 version. As a result, TF-dependent visualizations like PointCloud2 can now be displayed correctly on a web page when using a ROS 2 backend, resolving a critical compatibility issue.
This change has been tested and verified on ROS 2 Kilted with Ubuntu 24.04.

Resolves #948

### CODE REVIEW

**Comment by MatthijsBurgh** [comment]
@EzraBrooks this is a breaking change for ROS1. Time to branch of for ROS1?

**Comment by linglitel** [comment]
Hi, @MatthijsBurgh,thank you for your feedback,I'd like to think that my change was made exclusively within the ROS2TFClient class, which is intended for ROS 2 environments. The original TFClient for ROS 1 remains untouched.
If I understand wrongly, please correct me,

**Comment by MatthijsBurgh** [comment]
https://github.com/RobotWebTools/roslibjs/blob/0f6d12a552d5ee8f2173760c51cd1ac348ac0bde/examples/ros2_action_client.html#L46

This example doesn't include the `action` namespace. @EzraBrooks @sea-bass you know what the correct action type format is.

File: src/tf/ROS2TFClient.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ export default class ROS2TFClient extends EventEmitter {
         this.actionClient = new Action({
             ros: options.ros,
             name: this.serverName,
-            actionType: 'tf2_web_republisher_msgs/TFSubscription',
+            actionType: 'tf2_web_republisher_interfaces/action/TFSubscription',
```
Comment (MatthijsBurgh) [inline src/tf/ROS2TFClient.js]:
```suggestion
            actionType: 'tf2_web_republisher_interfaces/TFSubscription',
```

**Review by MatthijsBurgh — DISMISSED** [review]

File: src/tf/ROS2TFClient.js (hunk 1 above)
Comment (linglitel) [reply src/tf/ROS2TFClient.js]: I'm sorry I couldn't fully test it to see if it works properly because I don't have access to an RGB-D camera, but I did test the change and it worked without any errors. I think it works. Thanks for your feedback and changes.

**Review by bjsowa — APPROVED** [review]
